[package]
name = "tessera-indexer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
tessera-graph = { path = "../graph" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
