import type { DiagramData } from "./diagram-types";

export const DEMO_DATA: DiagramData = {
  nodes: [
    { id: "shopper",    type: "actor",     label: "Shopper",          r: 18 },
    { id: "place",      type: "useCase",   label: "Place Order",      r: 26 },
    { id: "contract",   type: "contract",  label: "Checkout v3",      r: 28, frozen: true, selected: true },
    { id: "order",      type: "aggregate", label: "Order",            r: 30 },
    { id: "payment",    type: "aggregate", label: "Payment",          r: 26, drift: true },
    { id: "adr",        type: "decision",  label: "ADR-031",          r: 16 },
    { id: "customer",   type: "aggregate", label: "Customer",         r: 22 },
    { id: "cart",       type: "aggregate", label: "Cart",             r: 20 },
    { id: "fraud",      type: "useCase",   label: "Fraud Check",      r: 18 },
    { id: "stripe",     type: "module",    label: "Stripe Gateway",   r: 16 },
    { id: "orderSvc",   type: "module",    label: "OrderService",     r: 16 },
    { id: "orderRepo",  type: "module",    label: "OrderRepo",        r: 15 },
    { id: "refund",     type: "contract",  label: "Refund v1",        r: 18 },
    { id: "pricing",    type: "contract",  label: "Pricing v2",       r: 16 },
  ],
  edges: [
    { id: "e1",  source: "shopper",  target: "place",     kind: "invokes" },
    { id: "e2",  source: "place",    target: "contract",  kind: "derives",  label: "derives" },
    { id: "e3",  source: "contract", target: "order",     kind: "shapes",   label: "shapes" },
    { id: "e4",  source: "place",    target: "cart",      kind: "reads" },
    { id: "e5",  source: "place",    target: "customer",  kind: "reads" },
    { id: "e6",  source: "cart",     target: "order",     kind: "becomes" },
    { id: "e7",  source: "order",    target: "payment",   kind: "requires", label: "requires" },
    { id: "e8",  source: "order",    target: "orderSvc",  kind: "impl" },
    { id: "e9",  source: "orderSvc", target: "orderRepo", kind: "impl" },
    { id: "e10", source: "payment",  target: "stripe",    kind: "impl",     drift: true },
    { id: "e11", source: "payment",  target: "fraud",     kind: "gates",    label: "gates" },
    { id: "e12", source: "adr",      target: "contract",  kind: "decides",  dashed: true },
    { id: "e13", source: "refund",   target: "order",     kind: "shapes" },
    { id: "e14", source: "pricing",  target: "contract",  kind: "feeds" },
    { id: "e15", source: "customer", target: "place",     kind: "triggers" },
  ],
};
