[package]
name = "tessera-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
serde = { workspace = true }
tauri = { workspace = true }
tauri-plugin-dialog = "2"
tessera-core = { workspace = true }
tessera-projects = { workspace = true }

[lints]
workspace = true
