[package]
name = "tessera-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
rfd = "0.16"
serde = { workspace = true }
tauri = { workspace = true }
tessera-core = { workspace = true }
tessera-projects = { workspace = true }

[lints]
workspace = true
